### ISSUE TITLE
error in run

### ISSUE THREAD

**Issue by bhralz** [izikeros/trend_classifier#4]
Hi there
to run your own sample I reach an error
plz check that:

\.conda\envs\at\lib\site-packages\trend_classifier\configuration.py", line 13, in Config
    alpha: float | None = 2

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by izikeros** [comment]
In code, there were type hints supported by python 3.10 onwards. Fixed in v0.1.8.

**Comment by bhralz** [comment]
Thanks,
I am working on anaconda the latest python 3.9.
So could you please check consistency with 3.9?
I think the waterfall propagation occured for example in configuration too.

**Comment by izikeros** [comment]
@bhralzz - if there is still an issue after upgrading to trend_classifier==0.1.8 please give me some more context e.g. tracebacks. It works for me on Python 3.9.16.

**Comment by bhralz** [comment]
yeah, it worked by python 3.9.
thanks

**Comment by majidebraa** [comment]
Python 3.8 still throws this error
